#ifndef CARROM_AUDIO_ASSETS_H
#define CARROM_AUDIO_ASSETS_H

/* Sound effects embedded at build time from the .ogg files in assets/audio (generated by CMake into audio_assets.c) */
typedef struct {
    const char* name;                 /* file name without extension, e.g. "coin_coin_1" */
    const unsigned char* data;
    int size;
} AudioAsset;

extern const AudioAsset audio_assets[];
extern const int audio_asset_count;

#endif
